site_name: ECE Makerspace Docs
# site_url: https://eez156.ece.ust.hk/docs/
# docs_dir : 'docs'

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

theme: 
  name: lantana
  locale: en
  logo: images/makerspace_logo.png
  favicon: images/makerspace_logo.png # This line points to your custom theme directory

visible_search : true

plugins:
    - search:
        lang : 'en'
        min_search_length: 2
    - awesome-pages

markdown_extensions:
    - lantana
    - lantana.alerts2
    - lantana.selector
    - lantana.extensions.mdx_embedly
    - lantana.extensions.mdx_wsid
    - attr_list
    - lantana.cards
    - lantana.mtables
    - footnotes
    - pymdownx.highlight:
       anchor_linenums: true
    - lantana.codeblock_copybtn
    - admonition
    - pymdownx.arithmatex:
       generic : true
    - md_in_html
    - pymdownx.details
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:mermaid2.fence_mermaid
    - lantana.mermaid_precompile
    - pymdownx.snippets
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.magiclink
    - pymdownx.striphtml
    - lantana.link_opennewtab
    - lantana.alerts
    - lantana.accordion
    - lantana.tabs


extra_css:
  - stylesheets/extra.css